let new_state = {
    side_content: null,
    http_request_done:0,
    geo_coordinates: [],
    posts: [],
    post: [],
    sectors: [],
    category: [],
    filter_search: {
        value: null,
        active: true,
    },
    filter_options: {
        active: false,
        placeholder: null,
        options: [],
    },
    filter_range: {
        active: false,
        value: null,
    },
    financement_type_list: [
        "Financement par dettes",
        "Financement par fonds propres",
        "Subventions publiques",
        "Crédits commerciaux",
    ],
    main_filter_options_selected: null,
    main_filter_options: [
        "Pays d'origine",
        "Secteur",
        "Pays de deploiement",
        "Année de création",
        "Nombre d'employé",
        "Stade",
        "Besoin de financement",
    ],
    country_list: [
        { option: "Afrique du Sud", en: "South Africa", label: "Afrique du Sud" },
        { option: "Algérie", en: "Algeria", label: "Algérie" },
        { option: "Angola", en: "Angola", label: "Angola" },
        { option: "Bénin", en: "Benign", label: "Bénin" },
        { option: "Botswana", en: "Botswana", label: "Botswana" },
        { option: "Burkina Faso", en: "Burkina Faso", label: "Burkina Faso" },
        { option: "Burundi", en: "Burundi", label: "Burundi" },
        { option: "Cameroun", en: "Cameroon", label: "Cameroun" },
        { option: "Cap-Vert", en: "Green cap", label: "Cap-Vert" },
        {
            option: "République centrafricaine",
            en: "Central African Republic",
            label: "République centrafricaine",
        },
        { option: "Comores", en: "Comoros", label: "Comores" },
        {
            option: "République du Congo",
            en: "Republic of Congo",
            label: "République du Congo",
        },
        {
            option: "République démocratique du Congo",
            en: "Democratic Republic of the Congo",
            label: "République démocratique du Congo",
        },
        { option: "Côte d’Ivoire", en: "Ivory Coast", label: "Côte d’Ivoire" },
        { option: "Djibouti", en: "Djibouti", label: "Djibouti" },
        { option: "Égypte", en: "Egypt", label: "Égypte" },
        { option: "Érythrée", en: "Eritrea", label: "Érythrée" },
        { option: "Éthiopie", en: "Ethiopia", label: "Éthiopie" },
        { option: "Gabon", en: "Gabon", label: "Gabon" },
        { option: "Gambie", en: "Gambia", label: "Gambie" },
        { option: "Ghana", en: "Ghana", label: "Ghana" },
        { option: "Guinée", en: "Guinea", label: "Guinée" },
        { option: "Guinée-Bissau", en: "Guinea-Bissau", label: "Guinée-Bissau" },
        {
            option: "Guinée équatoriale",
            en: "Equatorial Guinea",
            label: "Guinée équatoriale",
        },
        { option: "Kenya", en: "Kenya", label: "Kenya" },
        { option: "Lesotho", en: "Lesotho", label: "Lesotho" },
        { option: "Liberia", en: "Liberia", label: "Liberia" },
        { option: "Libye", en: "Libya", label: "Libye" },
        { option: "Madagascar", en: "Madagascar", label: "Madagascar" },
        { option: "Malawi", en: "Malawi", label: "Malawi" },
        { option: "Mali", en: "Mali", label: "Mali" },
        { option: "Maroc", en: "Morocco", label: "Maroc" },
        { option: "Maurice", en: "Maurice", label: "Maurice" },
        { option: "Mauritanie", en: "Mauritania", label: "Mauritanie" },
        { option: "Mozambique", en: "Mozambique", label: "Mozambique" },
        { option: "Namibie", en: "Namibia", label: "Namibie" },
        { option: "Niger", en: "Niger", label: "Niger" },
        { option: "Nigeria", en: "Nigeria", label: "Nigeria" },
        { option: "Ouganda", en: "Uganda", label: "Ouganda" },
        { option: "Rwanda", en: "Rwanda", label: "Rwanda" },
        {
            option: "São Tomé-et-Principe",
            en: "Sao Tome and Principe",
            label: "São Tomé-et-Principe",
        },
        { option: "Sénégal", en: "Senegal", label: "Sénégal" },
        { option: "Seychelles", en: "Seychelles", label: "Seychelles" },
        { option: "Sierra Leone", en: "Sierra Leone", label: "Sierra Leone" },
        { option: "Somalie", en: "Somalia", label: "Somalie" },
        { option: "Soudan", en: "Sudan", label: "Soudan" },
        { option: "Soudan du Sud", en: "South Sudan", label: "Soudan du Sud" },
        {
            option: "Eswatini (ex. Swaziland)",
            en: "Eswatini (ex. Swaziland)",
            label: "Eswatini (ex. Swaziland)",
        },
        { option: "Tanzanie", en: "Tanzania", label: "Tanzanie" },
        { option: "Tchad", en: "Chad", label: "Tchad" },
        { option: "Togo", en: "Togo", label: "Togo" },
        { option: "Tunisie", en: "Tunisia", label: "Tunisie" },
        { option: "Zambie", en: "Zambia", label: "Zambie" },
        { option: "Zimbabwe", en: "Zimbabwe", label: "Zimbabwe" },
    ],
    stade_list: [
        "Pré-seed",
        "Seed",
        "Pré-série A",
        "Série A",
        "Série B",
        "Série C",
    ],
    secteurs_list: [],
    category_list: [
        "E-santé et bien-être",
        "Éducation, formation professionnelle et emploi",
        "Agriculture et technologie alimentaire",
        "Services financiers et paiements",
        "Commerce électronique et vente au détail",
        "Logistique et chaînes d'approvisionnement",
        "Nouvelles mobilités et transports",
    ],
};

export let state = {
    uri: {
        url: "https://resilient.digital-africa.co/",
        api: "/wp-json/wp/v2/mini_fiche?_embed=author,wp:term,wp:featuredmedia&per_page=100",
        secteur_api: "wp-json/wp/v2/mf_secteurs",
    },
    filter: null,
    sub_filter: null,
    search_value: null,
    search_key: null,
    base_filter_selected: {
        label: "Filtrer par pays d'origine",
        option: 1,
    },
    base_filter: [{
            label: "Filtrer par pays d'origine",
            option: 1,
        },
        {
            label: "Filtrer par pays de déploiement",
            option: 2,
        },
    ],
    search: [],
    data: {},
    countries: [],
    loading: false,
    lang: "fr",
    ...new_state,
};